# --- General ---
datadir=/srv/bitcoin

# --- RPC ---
server=1
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=8332
rpccookieperms=group

# --- Network ---
listen=1
onlynet=onion
dnsseed=0
discover=0

proxy=127.0.0.1:9050
torcontrol=127.0.0.1:9051
listenonion=1

# --- Indexes ---
txindex=1
blockfilterindex=1
coinstatsindex=1

# --- Resource & Performance ---
dbcache=4000
maxconnections=40

# --- External Signer ---
signer=/usr/local/bin/hwi
